### ISSUE TITLE
Share Tabbar Style

### ISSUE THREAD

**Issue by jfamousket** [Nooo37/dots#1]
Hey nice dots, I have been stealing a lot from your setup lately and adding to my setup :laughing:
I noticed you have a specific `tabbar_style` for the bling module which you named as `mine` but I couldn't find it in your dots nor in the bling module, so would like you to share it here if possible or in some gist or something.
Thanks :)

**Comment by Nooo37** [comment]
You are right. I had the file in `awesome/bling/widget/tabbar` but since it is a submodule in this repo, the file doesn't show up. There you go: [https://0x0.st/-rVV.txt](https://0x0.st/-rVV.txt). I wanted to push it to bling with a different name after adding support for having it on the left or the right side which isn't difficult at all (just a little annoying) but I didn't bother anymore after having it the way I wanted to use it :sweat_smile:. So it only looks acceptable when the tabbar position is set to top or bottom atm. Someone else can do the PR if they want to (new tabbar styles are always a good idea). :eyes:

**Comment by Nooo37** [comment]
@jfamousket I hope that answers your question

**Comment by jfamousket** [comment]
Yeah for sure, I just tried it out works great :)
Yeah also thinking of great tabbar styles, really love the one you created right now though, will definitely make a PR if I make some good edits. 
Thanks :heart:
